export const skills = [
    { className: "devicon-html5-plain-wordmark colored", id: 1 },
    { className: "devicon-css3-plain-wordmark colored", id: 2 },
    { className: "devicon-javascript-plain colored", id: 3 },
    { className: "devicon-php-plain colored", id: 4 },
    { className: "devicon-python-plain", id: 5 },
    { className: "devicon-typescript-plain colored", id: 6 },
    { className: "devicon-react-original colored", id: 7 },
    { className: "devicon-angularjs-plain-wordmark colored", id: 8 },
    { className: "devicon-nodejs-plain-wordmark colored", id: 9 },
    { className: "devicon-express-original colored", id: 10 },
    { className: "devicon-nextjs-plain colored", id: 11 },
    { className: "devicon-dotnetcore-plain colored", id: 12 },
    { className: "devicon-redux-original colored", id: 13 },
    { className: "devicon-tailwindcss-original colored", id: 14 },
    { className: "devicon-bootstrap-plain colored", id: 15 },
    { className: "devicon-mysql-plain-wordmark colored", id: 16 },
    { className: "devicon-mongodb-plain-wordmark colored", id: 17 },
    { className: "devicon-firebase-plain-wordmark colored", id: 18 },
    { className: "devicon-docker-plain-wordmark colored", id: 19 },
    { className: "devicon-git-plain-wordmark colored", id: 20 },
    { className: "devicon-github-original colored", id: 21 },
    { className: "devicon-postman-plain colored", id: 22 },
    { className: "devicon-jira-plain-wordmark colored", id: 23 },
    { className: "devicon-figma-plain", id: 24 },
    { className: "devicon-canva-original colored", id: 25 },
];
